### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by starsprinter92** [pyt0xic/hyprfocus#5]
doesnt shrink, flash, or do anything

**Comment by pyt0xic** [comment]
I've finally got some time to look into this now, will hopefully have it working later today.

**Comment by pyt0xic** [comment]
Should be fixed now, I am going to close #4 and keep this issue open until I've gotten a confirmation from someone else that it works on their machine.

**Comment by obmutescences** [comment]
working with shrink. Check every day to see if it has been updated. thanks.

**Comment by fiskhest** [comment]
@pyt0xic after a `hyprpm update` hyprfocus again works on my machine. Thank you 🙏🏼

**Comment by pyt0xic** [comment]
Awesome, thank you for letting me know and sorry I took so long to fix it xD

**Comment by starsprinter92** [comment]
yes, it's fixed :)
